### ISSUE TITLE
Import Fails

### ISSUE THREAD

**Issue by inkrement** [logdna/python#1]
I tried to import the library, but I get following error:
```
Traceback (most recent call last):
  File ".....py", line 11, in <module>
    from logdna import LogDNAHandler
  File "/home/chris/Documents/...../env/lib/python3.5/site-packages/logdna/__init__.py", line 1, in <module>
    from logdna import LogDNAHandler
ImportError: cannot import name 'LogDNAHandler'
```

python 3.5, logdna 1.0.1

.. seems like Python 3 is not supported yet.

**Comment by alt3red** [comment]
Same issue here. Works for me in 2.7. Looking forward to a fix :)

**Comment by respectus** [comment]
Hi @inkrement and @alt3red, thanks for bringing this issue up. I have merged the newest PR and I've also refactored to ensure both python 2.7 and python 3 work. The newest release is currently on pip. Please let me know if this release doesn't work for you. Thanks for keeping up with this package!

**Comment by RajeshJeyapaul** [comment]
it still fails for me...import logDNAHanlder...using python 2.7
